export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ADD_TODO = 'ADD_TODO';
export const TODO_ERROR = 'TODO_ERROR';
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_USER = 'FETCH_USER';
export const USER_ERROR = 'USER_ERROR';
export const FETCH_LOCATION= "FETCH_LOCATION";
export const FETCH_CITY = 'FETCH_CITY';
export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR';
export const FETCH_USER_GUIDE_MATCH = 'FETCH_USER_GUIDE_MATCH';
export const FETCH_USER_GUIDE_MATCH_ERROR = 'FETCH_USER_GUIDE_MATCH_ERROR';


